version: '3.8'

services:
  aquashield-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aquashield_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - PORT=8000
    networks:
      - aquashield-net

networks:
  aquashield-net:
    driver: bridge